version: '3.1'

services:
  mongo:
    image: mongo
    container_name: db_price_prowler
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mongo_net

networks:
  mongo_net:

volumes:
  mongodb_data:
    driver: local
