version: '3'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    restart: always
    container_name: 'db'
    environment:
      SA_PASSWORD: 'Proyecto_1234' # Cambia esta contraseña por una segura
      ACCEPT_EULA: 'Y'
    ports:
      - '1433:1433'
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
